version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/
  - source: /ashok.png
    destination: /var/www/html/
hooks:
  ApplicationStop:
    - location: scripts/application-stop.sh
      timeout: 60
      runas: root

  BeforeInstall:
    - location: scripts/before-install.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/after-install.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/application-start.sh
      timeout: 60
      runas: root

  ValidateService:
    - location: scripts/validate-service.sh
      timeout: 60
      runas: root
